### PR TITLE
Issue Viewing Improvements

### PR DESCRIPTION
**Pull request by vkoves**
I've fixed an issue on the homepage where lines would show up if a stop had no issues, I've setup individual stop pages to display issues on stops, and made all displays of stops link to the individual stop page.

Comparison screenshots of homepage (Old VS New respectively):

An individual stop page:

screenshot from 2017-05-30 20-38-46

Also fixed search being missing due to long "Transit Network title". This bug was on `master` but was not deployed to production, which has a different title.

### CODE REVIEW

**Comment by AcademyInPeril** [comment]
Formatting of each section could be improved. For instance, the bookmark star should probably float to the top right rather than immediately following the title text for each station. However, that could be something that could go into a new issue, rather than being modified prior to integrating these changes. Thoughts?

**Comment by rjaltman** [comment]
@AcademyInPeril, I agree that the favorites star might work better fixed on the top (and possibly the right?) of the panel. Since the stop's text will differ, but the button is a common enough interaction, it might be frustrating looking for it in inconsistent places (where the text of the stop you can click anywhere with). 

I still haven't reviewed the rest of the changes locally yet, but from the screenshots, this looks pretty good (esp. compared to the originals, including that blank bar that used to show up)! Hoping to get a better review of this out soon (and as soon as we clear up discussions on the favorites star placement).

**Comment by vkoves** [comment]
All of these comments seem fair, and don't take too long to fix. However we could also consider implementing this mockup from @rjaltman:

pasted image at 2017_06_11 12_32 am

However this seems to encompass a lot of site wide changes that are probably beyond the scope of this PR. @AcademyInPeril and @rjaltman - what would you like me to fix before this PR is made, or is it clear to merge?

**Comment by rjaltman** [comment]
@vkoves, I wouldn't go through with full changes to meet that mockup quite yet...at least not in this PR. I do think that trying out a few new positions for the favorites / add buttons might be something to look into still, especially when lists (of nearby stops perhaps?) start to grow. I personally think the edits are good to go outside of this, but since this is primarily a style-and-layout-centered PR first, seeing these elements a bit too blurred with name areas when they don't have to be might cause an unnecessary condensed feel. Especially for a mobile-first platform, while it's important to get things out there as easily and visibly as possible, too much in one spot eliminates some of the typically expected view simplification on a phone screen.

I might be incorporating personal preference too much into what I think is "preferred" though, so I apologize. Mostly at this point, try out what things look like with position edits, and perhaps share findings with the group before moving on with this PR.

**Comment by AcademyInPeril** [comment]
I'm in agreement with Robert here: we should wrap up these current improvements and move them into the application before making any other changes outside the scope of this PR. If there's no significant objection from anybody, let's go ahead and merge at the end of the day.

**Pull request merged**
